layout: "main"
logger: "file"
template: template_toolkit
environment: development

engines:
  template_toolkit:
     start_tag: "[%"
     stop_tag: "%]"

kioku:
  dir: pastebindb

langs:
  C++: cpp.lang
  m4: m4.lang
  Haskell: haskell.lang
  Ada: ada.lang
  Makefile: makefile.lang
  Bib: bib.lang
  Bison: bison.lang
  C: c.lang
  CAML: caml.lang
  changelog: changelog.lang
  LaTeX: latex.lang
  conf: conf.lang
  C#: csharp.lang
  Bourne Shell: sh.lang
  CSS: css.lang
  diff: diff.lang
  XML: xml.lang
  Postscript: postscript.lang
  Fortran (Fixed): fixed-fortran.lang
  Fortran (Free): fortran.lang
  Flex: flex.lang
  glSlang: glsl.lang
  GLSL: glsl.lang
  haXe: haxe.lang
  HTML: html.lang
  INI: desktop.lang
  Java: java.lang
  Javascript: javascript.lang
  LDIF: ldap.lang
  Logtalk: logtalk.lang
  log: log.lang
  Lua: lua.lang
  Pascal: pascal.lang
  Perl: perl.lang
  PHP: php.lang
  pkgconfig: pc.lang
  Prolog: prolog.lang
  properties: properties.lang
  Python: python.lang
  Ruby: ruby.lang
  Scala: scala.lang
  Shell: sh.lang
  Slang: slang.lang
  sml: sml.lang
  RPM spec: spec.lang
  SQL: sql.lang
  syslog: log.lang
  tcl/tk: tcl.lang
  tcsh: sh.lang
  txt: nohilite.lang
  Xorg: xorg.lang
  yacc: bison.lang
  VB Script: vbscript.lang
  Erlang: erlang.lang 
  Assembler: asm.lang
  Applescript: applescript.lang
  DOS Batch: bat.lang 
  D: d.lang
  COBOL: cobol.lang
